INSERT INTO prefix (prefix, display) SELECT 'coll', 'collinear' WHERE NOT EXISTS (SELECT * FROM prefix);
-- INSERT INTO prefix (prefix, display) VALUES ('para', 'parallel');
-- INSERT INTO prefix (prefix, display) VALUES ('perp', 'perpendicular');
-- INSERT INTO prefix (prefix, display) VALUES ('midp', 'midpoint');
-- INSERT INTO prefix (prefix, display) VALUES ('circle', 'circle');
-- INSERT INTO prefix (prefix, display) VALUES ('cong', 'congruent');
-- INSERT INTO prefix (prefix, display) VALUES ('cyclic', 'concyclic');
-- INSERT INTO prefix (prefix, display) VALUES ('eqangle', 'equal angles');
-- INSERT INTO prefix (prefix, display) VALUES ('eqratio', 'equal ratios');
-- INSERT INTO prefix (prefix, display) VALUES ('simtri', 'similar triangles');
-- INSERT INTO prefix (prefix, display) VALUES ('contri', 'congruent triangles');
-- --